title: Chrome Audio Visualizer
description: > # this means to ignore newlines until "baseurl:"
  A audio visualizer chrome extension for all you music enjoying needs.
permalink: ':title/'

# Author Settings
author: Douile # add your name
author-img: avatar.jpg # add your photo
about-author: Web Developer # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: Douile # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: Chrome-Audio-Visualizer # add your discus identifier

# Tracker
analytics: UA-98384710-4 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

defaults:
 -
   scope:
     path: ""
   value:
     layout: post
     author: "Douile"
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
